# Cloud Cost Data Exploration
This notebook explores the AWS and Azure billing datasets to understand their structure and map them to the **FOCUS 1.0** ontology.

In [1]:
import pandas as pd
import numpy as np

# File paths
aws_path = 'data/aws_test-focus-00001.snappy_transformed.xls'
azure_path = 'data/focusazure_anon_transformed.xls'

# Load data
print("Loading AWS data...")
df_aws = pd.read_excel(aws_path)

print("Loading Azure data...")
df_azure = pd.read_excel(azure_path)

print("Data loaded successfully.")

Loading AWS data...
Loading Azure data...
Data loaded successfully.

## 1. AWS Data Overview

In [2]:
df_aws.head()

,AvailabilityZone,BilledCost,BillingAccountId,BillingAccountName,BillingCurrency,BillingPeriodEnd,BillingPeriodStart,ChargeCategory,ChargeClass,ChargeDescription,...,SkuId,SkuPriceId,SubAccountId,SubAccountName,x_CostCategories,x_Discounts,x_Operation,x_ServiceCode,x_UsageType,Tags
0,NaN,9.929700e-06,428183493173,gsafj-nalpybhq-zcn57-cebq,USD,2025-04-01 00:00:00+00:00,2025-03-01 00:00:00+00:00,Usage,NaN,$0.010 per GB - regional data transfer - in/ou...,...,5D2MW78KPJPRV7WA,5D2MW78KPJPRV7WA.JRTCKXETXF.6YS6EN2CT7,176817837311,gsafj-pbr-rdhvcfcg-abacebq,[],"[[""total_discount"", -2.8007e-06], [""bundled_di...",InterZone-In,AmazonEC2,APS2-DataTransfer-Regional-Bytes,"{""application"": ""GAJ578535"", ""environment"": ""S..."
1,NaN,0.000000e+00,428183493173,gsafj-nalpybhq-zcn57-cebq,USD,2025-04-01 00:00:00+00:00,2025-03-01 00:00:00+00:00,Usage,NaN,$0.0 per Request - request under the monthly f...,...,UD9FSDXZF2VVWH6Q,UD9FSDXZF2VVWH6Q.A429C66SYZ.6YS6EN2CT7,969729385293,gsafj-qpvf-pnzc-cebq,[],"[[""total_discount"", 0.0], [""bundled_discount"",...",GetRepositoryPermissionsPolicy,AWSCodeArtifact,APS2-Requests,NaN
2,NaN,1.010000e-08,428183493173,gsafj-nalpybhq-zcn57-cebq,USD,2025-04-01 00:00:00+00:00,2025-03-01 00:00:00+00:00,Usage,NaN,$0.098 per GB - next 40 TB / month data transf...,...,KRXM4TG87VW2NPHA,KRXM4TG87VW2NPHA.JRTCKXETXF.VF6T3GAUKQ,938828427530,gsafj-pf-pfbyhgvbaf-abacebq,[],"[[""total_discount"", -2.9e-09], [""bundled_disco...",ReadBucketPolicyStatus,AmazonS3,APS2-DataTransfer-Out-Bytes,"{""application"": ""FLG578978"", ""environment"": ""s..."
3,NaN,1.059541e-03,428183493173,gsafj-nalpybhq-zcn57-cebq,USD,2025-04-01 00:00:00+00:00,2025-03-01 00:00:00+00:00,Usage,NaN,$0.10 per GB-month of data storage,...,YBDKSSGX2GMZ62JV,YBDKSSGX2GMZ62JV.JRTCKXETXF.6YS6EN2CT7,741834794295,gsafj-nnv-qngncyngsbez-abacebq,[],"[[""total_discount"", -0.0002988447], [""bundled_...",APS2-TimedStorage-ByteHrs,AmazonECR,APS2-TimedStorage-ByteHrs,NaN
4,NaN,0.000000e+00,428183493173,gsafj-nalpybhq-zcn57-cebq,USD,2025-04-01 00:00:00+00:00,2025-03-01 00:00:00+00:00,Usage,NaN,$0.048 per provisioned MiBps-month of gp3 - As...,...,NR674TZUSQXFCVM8,NR674TZUSQXFCVM8.JRTCKXETXF.6YS6EN2CT7,57816637909,gsafj-pbecbengrvg-rdhvcceq-cebq,[],"[[""total_discount"", 0.0], [""bundled_discount"",...",CreateVolume-Gp3,AmazonEC2,APS2-EBS:VolumeP-Throughput.gp3,"{""application"": ""gsafj-pbecvg-rdhvc-cebq"", ""en..."

In [3]:
df_aws.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 48 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   AvailabilityZone            32 non-null     object
 1   BilledCost                  1000 non-null   float64
 2   BillingAccountId            1000 non-null   int64
 3   BillingAccountName          1000 non-null   object
 4   BillingCurrency             1000 non-null   object
 5   BillingPeriodEnd            1000 non-null   object
 6   BillingPeriodStart          1000 non-null   object
 7   ChargeCategory              1000 non-null   object
 8   ChargeClass                 0 non-null      float64
 9   ChargeDescription           1000 non-null   object
 10  ChargeFrequency             1000 non-null   object
 11  ChargePeriodEnd             1000 non-null   object
 12  ChargePeriodStart           1000 non-null   object
 13  CommitmentDiscountCategory  20 non-null     object
 14  CommitmentDiscountId        20 non-null     object
 15  CommitmentDiscountName      0 non-null      float64
 16  CommitmentDiscountStatus    20 non-null     object
 17  CommitmentDiscountType      20 non-null     object
 18  ConsumedQuantity            1000 non-null   float64
 19  ConsumedUnit                1000 non-null   object
 20  ContractedCost              1000 non-null   float64
 21  ContractedUnitPrice         1000 non-null   float64
 22  EffectiveCost               1000 non-null   float64
 23  InvoiceIssuerName           1000 non-null   object
 24  ListCost                    1000 non-null   float64
 25  ListUnitPrice               1000 non-null   float64
 26  PricingCategory             1000 non-null   object
 27  PricingQuantity             1000 non-null   float64
 28  PricingUnit                 1000 non-null   object
 29  ProviderName                1000 non-null   object
 30  PublisherName               1000 non-null   object
 31  RegionId                    1000 non-null   object
 32  RegionName                  993 non-null    object
 33  ResourceId                  919 non-null    object
 34  ResourceName                0 non-null      float64
 35  ResourceType                306 non-null    object
 36  ServiceCategory             1000 non-null   object
 37  ServiceName                 1000 non-null   object
 38  SkuId                       1000 non-null   object
 39  SkuPriceId                  1000 non-null   object
 40  SubAccountId                1000 non-null   int64
 41  SubAccountName              1000 non-null   object
 42  x_CostCategories            1000 non-null   object
 43  x_Discounts                 1000 non-null   object
 44  x_Operation                 984 non-null    object
 45  x_ServiceCode               1000 non-null   object
 46  x_UsageType                 1000 non-null   object
 47  Tags                        824 non-null    object
dtypes: float64(11), int64(2), object(35)
memory usage: 375.1+ KB

## 2. Azure Data Overview

In [4]:
df_azure.head()

,billedcost,billingaccountid,billingaccountname,billingaccounttype,billingcurrency,billingperiodend,billingperiodstart,chargecategory,chargeclass,chargedescription,...,x_skumetersubcategory,x_skuofferid,x_skuorderid,x_skuordername,x_skupartnumber,x_skuregion,x_skuservicefamily,x_skuterm,x_skutier,tags
0,0.033876,/providers/Microsoft.Billing/billingAccounts/9...,Genafcbeg sbe AFJ,Billing Account,AUD,2025-02-01,2025-01-01,Usage,NaN,Premium SSD Managed Disks - P10 LRS - AU East,...,Premium SSD Managed Disks,MS-AZR-0017P,NaN,NaN,AAD-18120,AU East,NaN,NaN,NaN,"{""application"": ""gsafj-rqnf-nanylgvpf-abacebq""..."
1,0.000000,/providers/Microsoft.Billing/billingAccounts/9...,Genafcbeg sbe AFJ,Billing Account,AUD,2025-02-01,2025-01-01,Usage,NaN,Rtn Preference: MGN - Standard Data Transfer I...,...,Rtn Preference: MGN,MS-AZR-0017P,NaN,NaN,Q5H-00019,AU East,NaN,NaN,NaN,"{""application"": ""qrsnhyg"", ""environment"": ""non..."
2,0.000296,/providers/Microsoft.Billing/billingAccounts/9...,Genafcbeg sbe AFJ,Billing Account,AUD,2025-02-01,2025-01-01,Usage,NaN,Microsoft Defender for Storage - Standard Tran...,...,Storage,MS-AZR-0017P,NaN,NaN,AAA-97331,NaN,NaN,NaN,NaN,"{""application"": ""gsafj-rqnf-nanylgvpf-abacebq""..."
3,0.000084,/providers/Microsoft.Billing/billingAccounts/9...,Genafcbeg sbe AFJ,Billing Account,AUD,2025-02-01,2025-01-01,Usage,NaN,Microsoft Defender for Storage - Standard Tran...,...,Storage,MS-AZR-0017P,NaN,NaN,AAA-97331,NaN,NaN,NaN,NaN,"{""application"": ""qrsnhyg"", ""environment"": ""Non..."
4,0.000128,/providers/Microsoft.Billing/billingAccounts/9...,Genafcbeg sbe AFJ,Billing Account,AUD,2025-02-01,2025-01-01,Usage,NaN,Azure Data Factory v2 - Cloud - External Pipel...,...,NaN,MS-AZR-0017P,NaN,NaN,AAD-19285,NaN,NaN,NaN,NaN,"{""application"": ""596760"", ""environment"": ""Tst""..."

In [5]:
df_azure.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 999 entries, 0 to 998
Data columns (total 96 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   billedcost                  999 non-null    float64
 1   billingaccountid            999 non-null    object
 2   billingaccountname          999 non-null    object
 3   billingaccounttype          999 non-null    object
 4   billingcurrency             999 non-null    object
 5   billingperiodend            999 non-null    datetime64[ns]
 6   billingperiodstart          999 non-null    datetime64[ns]
 7   chargecategory              999 non-null    object
 8   chargeclass                 0 non-null      float64
 9   chargedescription           999 non-null    object
 10  chargefrequency             999 non-null    object
 11  chargeperiodend             999 non-null    datetime64[ns]
 12  chargeperiodstart           999 non-null    datetime64[ns]
 13  commitmentdiscountid        0 non-null      float64
 14  commitmentdiscountname      0 non-null      float64
 15  commitmentdiscountquantity  0 non-null      float64
 16  commitmentdiscountstatus    0 non-null      float64
 17  commitmentdiscounttype      0 non-null      float64
 18  consumedquantity            999 non-null    float64
 19  consumedunit                999 non-null    object
 20  contractedcost              999 non-null    float64
 21  contractedunitprice         999 non-null    float64
 22  effectivecost               999 non-null    float64
 23  invoiceissuername           999 non-null    object
 24  listcost                    999 non-null    float64
 25  listunitprice               999 non-null    float64
 26  pricingcategory             999 non-null    object
 27  pricingquantity             999 non-null    float64
 28  pricingunit                 999 non-null    object
 29  providername                999 non-null    object
 30  publishername               999 non-null    object
 31  regionid                    999 non-null    object
 32  regionname                  999 non-null    object
 33  resourceid                  999 non-null    object
 34  resourcename                999 non-null    object
 35  resourcetype                999 non-null    object
 36  servicecategory             999 non-null    object
 37  servicename                 999 non-null    object
 38  skuid                       999 non-null    int64
 39  skupriceid                  999 non-null    int64
 40  subaccountid                999 non-null    object
 41  subaccountname              999 non-null    object
 42  subaccounttype              999 non-null    object
 43  x_accountid                 999 non-null    int64
 44  x_accountname               999 non-null    object
 45  x_accountownerid            999 non-null    object
 46  x_billedcostinusd           0 non-null      float64
 47  x_billedunitprice           999 non-null    float64
 48  x_billingaccountid          999 non-null    int64
 49  x_billingaccountname        999 non-null    object
 50  x_billingexchangerate       999 non-null    int64
 51  x_billingexchangeratedate   999 non-null    datetime64[ns]
 52  x_billingprofileid          999 non-null    int64
 53  x_billingprofilename        999 non-null    object
 54  x_contractedcostinusd       0 non-null      float64
 55  x_costallocationrulename    0 non-null      float64
 56  x_costcenter                805 non-null    object
 57  x_customerid                0 non-null      float64
 58  x_customername              0 non-null      float64
 59  x_effectivecostinusd        0 non-null      float64
 60  x_effectiveunitprice        999 non-null    float64
 61  x_invoiceid                 0 non-null      float64
 62  x_invoiceissuerid           0 non-null      float64
 63  x_invoicesectionid          999 non-null    int64
 64  x_invoicesectionname        999 non-null    object
 65  x_listcostinusd             0 non-null      float64
 66  x_partnercreditapplied      0 non-null      float64
 67  x_partnercreditrate         0 non-null      float64
 68  x_pricingblocksize          999 non-null    int64
 69  x_pricingcurrency           999 non-null    object
 70  x_pricingsubcategory        999 non-null    object
 71  x_pricingunitdescription    999 non-null    object
 72  x_publishercategory         999 non-null    object
 73  x_publisherid               999 non-null    object
 74  x_resellerid                0 non-null      float64
 75  x_resellername              0 non-null      float64
 76  x_resourcegroupname         997 non-null    object
 77  x_resourcetype              999 non-null    object
 78  x_serviceperiodend          0 non-null      float64
 79  x_serviceperiodstart        0 non-null      float64
 80  x_skudescription            999 non-null    object
 81  x_skudetails                314 non-null    object
 82  x_skuiscrediteligible       999 non-null    bool
 83  x_skumetercategory          999 non-null    object
 84  x_skumeterid                999 non-null    object
 85  x_skumetername              999 non-null    object
 86  x_skumetersubcategory       864 non-null    object
 87  x_skuofferid                999 non-null    object
 88  x_skuorderid                0 non-null      float64
 89  x_skuordername              0 non-null      float64
 90  x_skupartnumber             999 non-null    object
 91  x_skuregion                 451 non-null    object
 92  x_skuservicefamily          0 non-null      float64
 93  x_skuterm                   0 non-null      float64
 94  x_skutier                   0 non-null      float64
 95  tags                        994 non-null    object
dtypes: bool(1), datetime64[ns](5), float64(36), int64(8), object(46)
memory usage: 742.5+ KB

Identify the columns in both datasets that match the FOCUS 1.0 classes like `CostRecord`, `Service`, `Resource`, etc.